### ISSUE TITLE
Add NULL as a first class citizen of the Unity Container

### ISSUE THREAD

**Issue by ENikS** [unitycontainer/abstractions#102]
### Description
Current implementation does not recognize NULL as valid object.

### Problem
A lot of times NULL is a valid value for the dependency created by a Factory or registered as an instance. 

### Solution
Add NULL as a first class citizen to Unity system. 

### Impact
Existing code should not be impacted.

**Comment by GSPP** [comment]
When migrating from 3.3 to 4.1.3.0 this did have a compatibility impact. A custom `LifetimeManager` of mine returned `null` when no value was stored yet. This caused Unity to create a value and store it. Subsequent gets returned that value. Now the initial `return null;` causes `null` to be stored.

The code looked like this:

        public override object GetValue(ILifetimeContainer container = null)
        {
            return someDictionary.TryGetValue(key) ?? LifetimeManager.NoValue;
        }

Without the `?? LifetimeManager.NoValue` which is the fix.

I believe types deriving from `SynchronizedLifetimeManager` are not affected because there is special handling for `null` and `NoValue` there. My type derived directly from `LifetimeManager`.

I have fixed this by using the new `NoValue`. Notifying you of this because this might break other users.

**Comment by ENikS** [comment]
Yes, it is a breaking change and should be dealt with by lifetime manager designers. 

This issue documents the change so you could act accordingly.
